CREATE DATABASE duan1_final
GO
USE duan1_final
GO



CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(15) PRIMARY KEY NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NULL,
	SDT NVARCHAR(20) NOT NULL,
	VAITRO BIT NOT NULL DEFAULT 0,
	NGAYSINH DATE NOT NULL,
	EMAIL NVARCHAR(50) NULL,
);

CREATE TABLE KHACHHANG
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENKH NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(100) NULL,
	SDT NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NULL,
	EMAIL NVARCHAR(50) NULL,
	GIOITINH BIT NOT NULL DEFAULT 0
);



CREATE TABLE NHACUNGCAP 
(
	MANCC NVARCHAR(15) PRIMARY KEY NOT NULL,
	TENNCC NVARCHAR(50) NOT NULL,
	SDT NVARCHAR(20) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
);

CREATE TABLE LOAISANPHAM
(
	MALOAI NVARCHAR(15) PRIMARY KEY NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
);

CREATE TABLE SANPHAM
(
	MASP NVARCHAR(15) PRIMARY KEY NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	GIA FLOAT NOT NULL,
	SOLUONG INT NOT NULL,
	HINH NVARCHAR(100) NULL,
	MOTA NVARCHAR(100) NULL,
	MANCC NVARCHAR(15) NOT NULL,
	MALOAI NVARCHAR(15) NOT NULL,
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC) ON UPDATE CASCADE,
	FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI) ON UPDATE CASCADE, 
	UNIQUE(TENSP),
	CHECK(GIA > 0 AND SOLUONG > 0)
);

CREATE TABLE THANHTOAN
(
	MATT NVARCHAR(15)NOT NULL PRIMARY KEY,
	TENTT NVARCHAR(50) NOT NULL,	

);
 
CREATE TABLE DONHANG
(
	MADH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NGAYMUA DATE NOT NULL default getdate(),
	MAKH INT NOT NULL,
	MATT NVARCHAR(15) NOT NULL,
	MANV NVARCHAR(15) NOT NULL,

	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON UPDATE CASCADE,
	FOREIGN KEY (MATT) REFERENCES THANHTOAN(MATT) ON UPDATE CASCADE,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE,

);


CREATE TABLE CHITIETDONHANG
(
	MADH INT NOT NULL,
	MASP NVARCHAR(15) NOT NULL,
	SOLUONG INT NOT NULL,
	GIA FLOAT NOT NULL,

	PRIMARY KEY (MADH,MASP),
	FOREIGN KEY (MADH) REFERENCES DONHANG(MADH) ON UPDATE CASCADE,
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) ON UPDATE CASCADE,
);


INSERT INTO NHANVIEN VALUES('PHUCVH','123',N'VŨ HOÀNG PHÚC',N'ĐỒNG THÁP','0969141969',1,'2001-11-09','PHUCVHPS12860@FPT.EDU.VN')

INSERT INTO NHACUNGCAP VALUES('SS01','SAMSUNG','02839157310',N'Số 2, đường Hải Triều, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh')

INSERT INTO LOAISANPHAM VALUES('DT01',N'ĐIỆN THOẠI'),
									('PK01',N'PHỤ KIỆN'),
									('LT01',N'LAPTOP'),
									('TB01',N'MÁY TÍNH BẢNG')





INSERT INTO SANPHAM VALUES('SP01','GALAXY NOTE 20',900,40,'',N'','SS01','DT01')

INSERT INTO THANHTOAN VALUES ('TT01',N'THANH TOÁN TẠI QUẦY'),
								('TT02',N'CHUYỂN KHOẢN'),
								('TT03',N'THẺ TÍN DỤNG')

INSERT INTO KHACHHANG VALUES (N'NGUYỄN VĂN TÈO',N'TP HCM','0969841264','19751206','NGUYENVANTEO123@GMAIL.COM',0)

INSERT INTO DONHANG VALUES ('20201106',1,'TT01','PHUCVH')

INSERT INTO CHITIETDONHANG VALUES(1,'SP01',1,'900')


SELECT * FROM SANPHAM
SELECT * FROM LOAISANPHAM